[versions]
jetbrains-annotations = "26.0.2"
mixin = "0.8.7"
modDevGradle = "2.0.143"

[libraries]
jetbrains-annotations   = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
mixin                   = { module = "org.spongepowered:mixin", version.ref = "mixin" }

[plugins]
modDevGradle            = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }
