[versions]
mixinExtras = "0.5.4"
jei = "19.25.0.325"
emi = "1.1.24+1.21.1"

## Modrinth Maven ##
jade = "15.10.6+neoforge"
sodium = "mc1.21.1-0.6.9-neoforge"
iris = "1.8.12+1.21.1-neoforge"
modernfix = "5.27.20+mc1.21.1"
spark = "1.10.124-neoforge-1.21.1"
create = "6.0.10-281"
ponder = "1.0.87+mc1.21.1"
flywheel = "1.0.6-44"
registrate = "MC1.21-1.3.0+67"
sable = "2.0.3"
sable-companion = "1.6.0"

[libraries]
mixinExtras         = { module = "io.github.llamalad7:mixinextras-neoforge", version.ref = "mixinExtras" }
jei-api             = { module = "mezz.jei:jei-1.21.1-neoforge-api", version.ref = "jei" }
jei-impl            = { module = "mezz.jei:jei-1.21.1-neoforge", version.ref = "jei" }
emi                 = { module = "dev.emi:emi-neoforge", version.ref = "emi" }
spark               = { module = "maven.modrinth:spark", version.ref = "spark" }
jade                = { module = "maven.modrinth:jade", version.ref = "jade" }
modernfix           = { module = "maven.modrinth:modernfix", version.ref = "modernfix" }
sodium              = { module = "maven.modrinth:sodium", version.ref = "sodium" }
iris                = { module = "maven.modrinth:iris", version.ref = "iris" }
create              = { module = "com.simibubi.create:create-1.21.1", version.ref = "create" }
ponder              = { module = "net.createmod.ponder:ponder-neoforge", version.ref = "ponder" }
flywheel-api        = { module = "dev.engine-room.flywheel:flywheel-neoforge-api-1.21.1", version.ref = "flywheel" }
flywheel-impl       = { module = "dev.engine-room.flywheel:flywheel-neoforge-1.21.1", version.ref = "flywheel" }
registrate          = { module = "com.tterrag.registrate:Registrate", version.ref = "registrate" }
sable               = { module = "dev.ryanhcode.sable:sable-neoforge-1.21.1", version.ref = "sable" }
sable-rapier        = { module = "dev.ryanhcode.sable:sable-sable_rapier-1.21.1", version.ref = "sable" }
sable-companion     = { module = "dev.ryanhcode.sable-companion:sable-companion-common-1.21.1", version.ref = "sable-companion" }
